export type Locale = 'en' | 'zh'

export const strings = {
  en: {
    nav: { home: 'Home', records: 'Records', wishes: 'Wishes', profile: 'Profile' },
    common: {
      save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', back: 'Back', confirm: 'Confirm', yuan: '¥', closeAnywhere: 'Tap anywhere to close',
    },
    profile: {
      title: 'Profile', language: 'Language', english: 'English', chinese: 'Chinese', theme: 'Theme',
      themeSignature: 'Signature', themeLight: 'Light', themeDark: 'Dark', clearData: 'Clear local data (dev)',
      clearDataConfirm: 'Clear all local data? This cannot be undone.',
      languageHint: 'Switch app language preference',
      subtitle: 'MoneyRead · Read your money',
      reportHint: 'Weekly / Monthly · Export',
      localOnly: 'Local storage only · Data stays in this browser',
      devTools: 'Developer Tools',
      devToolsHint: 'Clear all local records/wishes/achievements for testing.',
      dailyLimit: 'Daily spending limit',
      dailyLimitHint: 'Optional. Leave empty to turn off. Warns once per day when you go over.',
      dailyLimitPlaceholder: 'e.g. 300',
    },
    dashboard: {
      thisMonth: 'This Month', thisMonthExpense: 'This month expense', income: 'Income', balance: 'Balance',
      dailyAverage: 'Daily average', vsLastMonth: 'vs last month', topCategories: 'Top categories · 5',
      noExpenseData: 'No expense data yet', wishProgress: 'Wish progress', all: 'All',
      createFirstWish: 'Create your first wish →', recentAchievements: 'Recent achievements',
      firstAchievementHint: 'Add a record to unlock your first achievement',
      morning: 'Good morning', afternoon: 'Good afternoon', evening: 'Good evening',
      quickTemplates: 'Quick templates',
      quickTemplatesHint: 'Add shortcuts for expenses you repeat often.',
      templateRecorded: 'Recorded',
      saveAsTemplate: 'Save as template?',
      templatesMax: 'Maximum 8 templates',
      dailyLimitProgress: 'Today vs daily limit',
    },
    records: {
      title: 'Records', all: 'All', today: 'Today', week: 'This week', month: 'This month',
      search: 'Search notes...', noRecords: 'No records found', noMatch: 'No records match filters',
      editRecord: 'Edit record', deleteRecordConfirm: 'Delete this record?',
      expense: 'Expense', income: 'Income',
    },
    wishes: {
      title: 'Wishes', new: 'New', subtitle: 'Up to 5 active wishes · Save toward what matters',
      active: 'Active wishes', create: 'Create wish →', memories: 'Wish memories', completed: 'Completed ✅',
      deleteConfirm: 'Delete this wish?', deleteDoneConfirm: 'Delete this completed wish?',
      createWish: 'Create Wish', name: 'Wish name', target: 'Target amount', imageOptional: 'Wish image (optional)',
      image: 'Wish image',
      deadlineOptional: 'Deadline (optional)', deadlineYear: 'Year', deadlineMonth: 'Month', deadlineDay: 'Day',
      deadlinePlaceholderY: 'YYYY', deadlinePlaceholderM: 'MM', deadlinePlaceholderD: 'DD', deadlineInvalid: 'Enter a valid date',
      max5: 'Maximum 5 active wishes', submit: 'Create wish',
      notFound: 'Wish not found', backToList: 'Back to list', deadline: 'Deadline',
      addDeposit: 'Add deposit', amount: 'Amount', deposit: 'Deposit', depositRecords: 'Deposit records',
      planHint: 'Plan daily savings before the deadline; small deposits still move progress forward.',
      bothDeleteHint: 'Both active and completed wishes can be deleted.', milestonesReached: 'Milestones reached',
      noRecords: 'No records', grantedTitle: 'Wish granted!',
    },
    achievements: {
      title: 'Achievements',
      unlocked: 'Unlocked',
      hidden: 'Hidden achievement',
      hiddenHint: 'Condition appears after unlock',
      unlockedBanner: 'Achievement unlocked',
      hiddenDesc: '???',
    },
    dna: {
      title: 'Spending DNA', need20: 'Need 20+ records to generate Spending DNA', current: 'Current',
      records: 'records', generate: 'Generate DNA', updatedAt: 'Updated at', refreshHint: 'Refreshes monthly on the 1st', refresh: 'Refresh now',
      refreshing: 'Updating…', refreshDone: 'Updated',
      dimensions: { frequency: 'Frequency', concentration: 'Concentration', timePattern: 'Time pattern', volatility: 'Volatility' },
    },
    report: {
      title: 'Report Card', weekly: 'Weekly Report', monthly: 'Monthly Report', totalSpending: 'Total spending',
      dailyAvg: 'Daily avg', vsPrevious: 'vs previous', topCategories: 'Top categories', biggest: 'Biggest expense:',
      wishSnapshot: 'Wish snapshot', monthDNA: "This month's DNA", achievements: 'Achievements:', exporting: 'Exporting...', savePng: 'Save PNG',
      footer: 'moneyread · Read your money. Ready your future.',
    },
    onboarding: {
      next: 'Next',
      skip: 'Skip',
      getStarted: 'Get started',
      step1Title: 'Welcome to MoneyRead!',
      step1Body: 'Track money, save for wishes, and earn achievements — stored only on this device.',
      step2Title: 'Log spending & income',
      step2Body: 'Tap the + button to record an expense or income in seconds.',
      step3Title: 'Save toward wishes',
      step3Body: 'Open Wishes to set a goal and add deposits over time.',
      step4Title: 'Unlock achievements',
      step4Body: 'Open Profile → Achievements to see progress and unlock conditions.',
    },
    templates: {
      newTitle: 'New template',
      editTitle: 'Edit template',
      name: 'Template name',
      save: 'Save',
      delete: 'Delete',
      deleteConfirm: 'Delete this template?',
      menu: 'Template actions',
    },
    dailyLimit: {
      bannerTitle: 'Daily limit reached',
      bannerBody: 'Spent ¥{spent} today · limit ¥{limit}',
    },
    image: { upload: 'Upload image', change: 'Change image', preview: 'Wish image preview', support: 'Supports jpg/png/webp/gif, max 2MB', typeError: 'Only jpg/png/webp/gif', sizeError: 'Image must be <= 2MB' },
    recordForm: {
      amount: 'Amount', expense: 'Expense', income: 'Income', category: 'Category', noteOptional: 'Note (optional)',
      notePlaceholder: 'Up to 50 chars', date: 'Date', confirm: 'Confirm', addRecord: 'Add record', editRecord: 'Edit record',
      oneDot: 'Only one decimal point allowed', twoDecimal: 'Up to 2 decimal places', numberOnly: 'Numbers only', close: 'Close',
    },
    categoryNames: {
      food: 'Food', milkTea: 'Bubble tea', shopping: 'Shopping', transport: 'Transport', digital: 'Subscriptions',
      entertainment: 'Entertainment', study: 'Study', medical: 'Health', social: 'Social', other_exp: 'Other',
      allowance: 'Allowance', parttime: 'Part-time', redpacket: 'Gift money', resale: 'Resale', other_inc: 'Other',
    },
    achievementNames: {
      first_record: 'First Steps', streak_7: 'On a Roll', streak_30: 'Habit Formed', records_100: 'Logging Pro',
      records_1000: 'Thousand Entries', all_categories: 'Category Master', first_deposit: 'Seed Planted', first_wish_done: 'Wish Granted',
      wishes_5: 'Wish Collector', wish_100: 'Hundred Club', wish_1000: 'Thousand Club', daily_under_50: 'Penny Pincher',
      zero_spend_day: 'Zero Day', weekend_low: 'Chill Weekend', midnight_shop: 'Night Owl Spender', milktea_20: 'Boba Addict', moonlight_awaken: 'Comeback Kid',
    },
    achievementDesc: {
      first_record: 'Add your first record.',
      streak_7: 'Record spending or income on 7 consecutive days.',
      streak_30: 'Keep your recording streak for 30 consecutive days.',
      records_100: 'Reach 100 total records.',
      records_1000: 'Reach 1,000 total records.',
      all_categories: 'Use every preset expense category at least once.',
      first_deposit: 'Deposit savings into any wish.',
      first_wish_done: 'Complete any wish.',
      wishes_5: 'Complete 5 wishes.',
      wish_100: 'Accumulate ¥100 or more in a single wish.',
      wish_1000: 'Accumulate ¥1,000 or more in a single wish.',
      daily_under_50: 'Last month had spending and daily average was under ¥50.',
      zero_spend_day: 'Have at least one calendar day with no expenses between two days you did spend.',
      weekend_low: 'Spend under ¥30 total on the most recent Saturday–Sunday (after 8+ records).',
      midnight_shop: 'Log an expense between midnight and 5:00 a.m.',
      milktea_20: 'Log 20 or more bubble-tea category expenses.',
      moonlight_awaken: 'Last month expenses exceeded income; this month income exceeds expenses (with some spending).',
    },
  },
  zh: {
    nav: { home: '首页', records: '账单', wishes: '心愿', profile: '我的' },
    common: { save: '保存', cancel: '取消', delete: '删除', edit: '编辑', back: '返回', confirm: '确认', yuan: '¥', closeAnywhere: '点击任意处关闭' },
    profile: {
      title: '我的', language: '语言', english: '英文', chinese: '中文', theme: '主题',
      themeSignature: '签名紫', themeLight: '浅色', themeDark: '深色', clearData: '清空本地数据（开发）',
      clearDataConfirm: '确认清空所有本地数据？此操作不可恢复。', languageHint: '切换应用显示语言',
      subtitle: 'MoneyRead · 看懂你的钱',
      reportHint: '周报 / 月报 · 导出分享',
      localOnly: '本地存储 · 数据仅保存在本机浏览器',
      devTools: '开发工具',
      devToolsHint: '清空所有本地账单/心愿/成就数据，便于重复测试流程。',
      dailyLimit: '每日支出上限',
      dailyLimitHint: '选填。留空即关闭。超出时每天最多提醒一次。',
      dailyLimitPlaceholder: '例如 300',
    },
    dashboard: {
      thisMonth: '本月概览', thisMonthExpense: '本月支出', income: '收入', balance: '结余',
      dailyAverage: '日均消费', vsLastMonth: '较上月支出', topCategories: '分类占比 · Top 5',
      noExpenseData: '暂无支出数据', wishProgress: '心愿进度', all: '全部', createFirstWish: '创建第一个心愿 →',
      recentAchievements: '最近成就', firstAchievementHint: '记一笔，解锁第一个成就',
      morning: '早上好', afternoon: '下午好', evening: '晚上好',
      quickTemplates: '快捷模板',
      quickTemplatesHint: '给常重复的支出建一键记账。',
      templateRecorded: '已记账',
      saveAsTemplate: '存为模板？',
      templatesMax: '最多 8 个快捷模板',
      dailyLimitProgress: '今日支出与上限',
    },
    records: {
      title: '账单', all: '全部', today: '今天', week: '本周', month: '本月',
      search: '搜索备注…', noRecords: '暂无记录', noMatch: '没有符合筛选条件的记录',
      editRecord: '编辑记录', deleteRecordConfirm: '确定删除这条记录？', expense: '支出', income: '收入',
    },
    wishes: {
      title: '心愿单', new: '新建', subtitle: '同时最多 5 个进行中 · 攒钱为心愿服务',
      active: '进行中', create: '创建心愿 →', memories: '心愿回忆录', completed: '已达成 ✅',
      deleteConfirm: '确认删除这个心愿？', deleteDoneConfirm: '确认删除这个已达成心愿？',
      createWish: '新建心愿', name: '心愿名称', target: '目标金额（元）', imageOptional: '心愿图片（可选）',
      image: '心愿图片',
      deadlineOptional: '截止日期（可选）', deadlineYear: '年', deadlineMonth: '月', deadlineDay: '日',
      deadlinePlaceholderY: '2025', deadlinePlaceholderM: '01', deadlinePlaceholderD: '15', deadlineInvalid: '请输入有效日期',
      max5: '已达到 5 个进行中上限', submit: '创建心愿',
      notFound: '未找到心愿', backToList: '返回列表', deadline: '截止',
      addDeposit: '存一笔', amount: '金额（元）', deposit: '存入', depositRecords: '存入记录',
      planHint: '距离截止还可按日规划；坚持小额存入也能推进进度条。', bothDeleteHint: '进行中和已达成都可以删除',
      milestonesReached: '已达成里程碑', noRecords: '暂无', grantedTitle: '心愿达成！',
    },
    achievements: {
      title: '成就墙',
      unlocked: '已解锁',
      hidden: '隐藏成就',
      hiddenHint: '解锁后显示条件',
      unlockedBanner: '成就解锁',
      hiddenDesc: '???',
    },
    dna: {
      title: '消费人格', need20: '累计记账满 20 笔后生成人格卡片', current: '当前', records: '笔',
      generate: '生成人格', updatedAt: '更新于', refreshHint: '每月 1 日可刷新维度', refresh: '手动刷新',
      refreshing: '更新中…', refreshDone: '已更新',
      dimensions: { frequency: '消费频率', concentration: '集中度', timePattern: '时段', volatility: '波动' },
    },
    report: {
      title: '消费报告', weekly: '周报', monthly: '月报', totalSpending: '总支出',
      dailyAvg: '日均', vsPrevious: '较上期', topCategories: 'Top 分类', biggest: '最大单笔：',
      wishSnapshot: '心愿快照', monthDNA: '本月人格', achievements: '成就：', exporting: '导出中…', savePng: '保存图片 PNG',
      footer: 'moneyread · 看懂你的钱，也看见你的未来。',
    },
    onboarding: {
      next: '下一步',
      skip: '跳过',
      getStarted: '开始使用',
      step1Title: '欢迎使用 MoneyRead！',
      step1Body: '记账、攒心愿、解锁成就——数据只保存在本机。',
      step2Title: '记录收支',
      step2Body: '点底部或侧栏的「+」快速记一笔支出或收入。',
      step3Title: '心愿攒钱',
      step3Body: '打开「心愿」设定目标，随时存入零钱推进进度。',
      step4Title: '成就进度',
      step4Body: '在「我的 → 成就墙」查看条件与解锁进度。',
    },
    templates: {
      newTitle: '新建模板',
      editTitle: '编辑模板',
      name: '模板名称',
      save: '保存',
      delete: '删除',
      deleteConfirm: '删除该模板？',
      menu: '模板操作',
    },
    dailyLimit: {
      bannerTitle: '已超过今日支出上限',
      bannerBody: '今日已花 ¥{spent} · 上限 ¥{limit}',
    },
    image: { upload: '上传图片', change: '更换图片', preview: '心愿图片预览', support: '支持 jpg/png/webp/gif，最大 2MB', typeError: '仅支持 jpg/png/webp/gif', sizeError: '图片不能超过 2MB' },
    recordForm: {
      amount: '金额（元）', expense: '支出', income: '收入', category: '分类', noteOptional: '备注（可选）',
      notePlaceholder: '最多 50 字', date: '日期', confirm: '确认记账', addRecord: '记一笔', editRecord: '编辑记录',
      oneDot: '只能输入一个小数点', twoDecimal: '最多保留两位小数', numberOnly: '只能输入数字', close: '关闭',
    },
    categoryNames: {
      food: '吃饭', milkTea: '奶茶饮品', shopping: '购物', transport: '交通', digital: '数码订阅',
      entertainment: '娱乐', study: '学习', medical: '医疗', social: '社交', other_exp: '其他',
      allowance: '生活费', parttime: '兼职', redpacket: '红包', resale: '闲鱼回血', other_inc: '其他',
    },
    achievementNames: {
      first_record: '初来乍到', streak_7: '坚持就是胜利', streak_30: '习惯养成', records_100: '记账达人',
      records_1000: '千笔之约', all_categories: '分类大师', first_deposit: '种子选手', first_wish_done: '小目标达成',
      wishes_5: '心愿收割机', wish_100: '百元里程碑', wish_1000: '千元俱乐部', daily_under_50: '精打细算',
      zero_spend_day: '零消费日', weekend_low: '佛系周末', midnight_shop: '深夜剁手', milktea_20: '奶茶续命', moonlight_awaken: '月光族觉醒',
    },
    achievementDesc: {
      first_record: '添加第一条账单记录。',
      streak_7: '连续 7 天都有记账（支出或收入）。',
      streak_30: '连续 30 天保持记账习惯。',
      records_100: '累计记账达到 100 笔。',
      records_1000: '累计记账达到 1000 笔。',
      all_categories: '每个预设支出分类都至少记过一笔。',
      first_deposit: '向任意心愿存入第一笔金额。',
      first_wish_done: '完成任意一个心愿。',
      wishes_5: '累计完成 5 个心愿。',
      wish_100: '单个心愿累计存入达到 ¥100 及以上。',
      wish_1000: '单个心愿累计存入达到 ¥1000 及以上。',
      daily_under_50: '上月有支出且日均支出低于 ¥50。',
      zero_spend_day: '在两笔支出之间的日历上，存在完全没有支出的某一天。',
      weekend_low: '在已有 8 笔以上记录时，最近一个完整周末两天总支出低于 ¥30。',
      midnight_shop: '在凌晨 0:00–5:00 之间记下一笔支出。',
      milktea_20: '「奶茶饮品」分类累计记账 20 笔及以上。',
      moonlight_awaken: '上月支出大于收入，本月收入大于支出且本月仍有支出。',
    },
  },
} as const

export function getStrings(locale: Locale) {
  return strings[locale]
}

