export type ThemeKey = 'signature' | 'light' | 'dark'

export const themes: Record<ThemeKey, Record<string, string>> = {
  signature: {
    '--color-primary': '#6C2BD9',
    '--color-primary-light': '#8B5CF6',
    '--color-primary-dark': '#4C1D95',
    '--color-accent': '#BFFF00',
    '--color-background': '#F5F2FF',
    '--color-surface': '#FFFFFF',
    '--color-text': '#1A1A2E',
    '--color-text-secondary': '#6B7280',
    '--color-hot': '#FF3366',
    '--color-electric': '#00D4FF',
    '--color-solar': '#FFB800',
    '--color-border': '#E5E7EB',
  },
  light: {
    '--color-primary': '#2563EB',
    '--color-primary-light': '#3B82F6',
    '--color-primary-dark': '#1D4ED8',
    '--color-accent': '#F59E0B',
    '--color-background': '#FFFFFF',
    '--color-surface': '#F8FAFC',
    '--color-text': '#0F172A',
    '--color-text-secondary': '#64748B',
    '--color-hot': '#EF4444',
    '--color-electric': '#06B6D4',
    '--color-solar': '#F59E0B',
    '--color-border': '#E2E8F0',
  },
  dark: {
    '--color-primary': '#A78BFA',
    '--color-primary-light': '#C4B5FD',
    '--color-primary-dark': '#7C3AED',
    '--color-accent': '#BFFF00',
    '--color-background': '#0F0F1A',
    '--color-surface': '#1A1A2E',
    '--color-text': '#F1F5F9',
    '--color-text-secondary': '#94A3B8',
    '--color-hot': '#FF6B8A',
    '--color-electric': '#5CEAFF',
    '--color-solar': '#FBBF24',
    '--color-border': '#2D2D44',
  },
}
